FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ALPACA - Communitation

提供各種channel發送訊息給客戶

# Group 系統設定

## 系統參數 [/sys]

### 系統參數設定 [POST]

+ Response 200

### 取得系統參數 [GET]

+ Response 200

# Group SMS
## 訊息 [/sms]

### 列出所有簡訊清單 [GET /sms{?status,userId}]

+ Parameters
    + status (enum[number], optional) - 狀態 
        + Members
            + `0` - 未發送 
            + `1` - 發送成功 
            + `-1` - 發送失敗
    + userId (number, optional)

+ Request Sample1 (text/plain)
    
    + Headers
    
            authorize: qpnasdfasdf
    

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "status": 0,
                "userId": "S1234"
                "sendDateTime": "2015-09-21 13:20:00"
            },
            {
                "id": 2,
                "status": 0,
                "userId": "S1234"
                "sendDateTime": "2015-09-21 13:20:00"
            }
        ]
        
+ Request Sample2 (text/plain)

+ Response 500


### 發送簡訊 [POST]

+ Response 201

# Group Mail
## 訊息 [/mail]

### 發送訊息 [POST]

+ Response 201

### 取得訊息清單 [GET]

+ Response 200

# Group Line

## 登入 [/line/login]
### 帳號&密碼 登入 [POST]

+ Response 200 (application/json)

### Token 登入 [POST /line/login/token/{token}]

+ Response 201

## 登出 [/line/logout]
### 登出 [POST]

+ Response 201

## 聯絡人清單 [/line/contacts]
### 取得聯絡人清單 [GET /line/contacts{?limit,page}]

+ Response 200

## 聯絡人詳細資料 [/line/contact]
### uId比對 [GET /line/contact/{uId}]

+ Response 200

### 自定義名稱比對 [GET /line/contact{?overrideName}]

+ Response 200

## 訊息 [/line/msg]

### 單一使用者發送訊息 [POST /line/msg/{uId}]

+ Response 201

### 取得訊息清單 [GET]

+ Response 200
